name: Compilar Ejecutable Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    # Bajamos la configuración a Node 18 para asegurar total compatibilidad con pkg
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: |
        if (Test-Path package.json) {
          npm install
        }

    - name: Instalar empaquetador globalmente
      run: npm install -g pkg

    # Aquí cambiamos el target a node18 para que no marque el error de compatibilidad
    - name: Compilar aplicacion a .exe
      run: pkg main.js --targets node18-win-x64 --output dist/MiAplicacion.exe

    - name: Subir el archivo .exe como Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Aplicacion-Windows-EXE
        path: dist/MiAplicacion.exe
